### ISSUE TITLE
[Bug]: 4e path issue

### ISSUE THREAD

**Issue by drsora** [genetics-of-dna-methylation-consortium/godmc_phase2#62]
### Contact Details

sonja.rajic@tuni.fi

### Scripts

04e-single-site-analysis.sh

### What happened?

Script ran successfully but failed at moving a file. I think there's an issue with the path. 

### R version

4.4.0 (April, 2024)

### Python version

None

### Relevant log output

```shell
experiment finished in 1127.22897887 s
Closing remaining open files:/data/sonja/godmc/processed_data/hase/hase_converting/probes/YFS_G1.h5...done/home/drsora/godmc_phase2/resources/bin/hase/data/ref-hrc.ref_info.h5...done
mv: target '/data/sonja/godmc/results/04/mapping/' is not a directory
```

**Comment by drsora** [comment]
I can. Our server is busy at the moment but I'll do it first thing next week.

**Comment by drsora** [comment]
This is the error I get now when I try to run 04e on Chris branch:

Traceback (most recent call last):
  File "/home/drsora/godmc_phase2/resources/bin/hase/hase.py", line 8, in <module>
    from hdgwas.meta_classic import CohortAnalyser
  File "/home/drsora/godmc_phase2/resources/bin/hase/hdgwas/meta_classic.py", line 6, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by epzjlm** [comment]
As pandas should already be installed I think you need to load the python environment in each script:

conda activate hase_py2

**Comment by drsora** [comment]
I am currently halfway through running 03e on G0, I'll try that as soon as that's done, so probably tomorrow, and let you know.

**Comment by drsora** [comment]
4a ran okay, 4b is giving this error:

Traceback (most recent call last):
  File "/home/drsora/godmc_phase2/resources/bin/hase/added/invert_probes.py", line 56, in <module>
    inv_probes(args.probes_folder, args.project_name)
  File "/home/drsora/godmc_phase2/resources/bin/hase/added/invert_probes.py", line 19, in inv_probes
    os.rename(old_original, new_original)
OSError: [Errno 2] No such file or directory

**Comment by drsora** [comment]
Also, I tried running 04a with YFS G0 data, as that's not gone through 3 but I get this:

`Traceback (most recent call last):
  File "/home/drsora/godmc_phase2/resources/bin/hase/hase.py", line 913, in <module>
    sys.exit(main())
  File "/home/drsora/godmc_phase2/resources/bin/hase/hase.py", line 192, in main
    G.plink2hdf5(out=args.out)
  File "/home/drsora/godmc_phase2/resources/bin/hase/hdgwas/converter.py", line 168, in plink2hdf5
    self.convert_probes()
  File "/home/drsora/godmc_phase2/resources/bin/hase/hdgwas/converter.py", line 112, in convert_probes
    complib='zlib',complevel=9, min_itemsize = 45)
  File "/home/drsora/.conda/envs/hase_py2/lib/python2.7/site-packages/pandas/core/generic.py", line 2377, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "/home/drsora/.conda/envs/hase_py2/lib/python2.7/site-packages/pandas/io/pytables.py", line 274, in to_hdf
    f(store)
  File "/home/drsora/.conda/envs/hase_py2/lib/python2.7/site-packages/pandas/io/pytables.py", line 266, in <lambda>
    f = lambda store: store.append(key, value, **kwargs)
  File "/home/drsora/.conda/envs/hase_py2/lib/python2.7/site-packages/pandas/io/pytables.py", line 986, in append
    **kwargs)
  File "/home/drsora/.conda/envs/hase_py2/lib/python2.7/site-packages/pandas/io/pytables.py", line 1415, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)
  File "/home/drsora/.conda/envs/hase_py2/lib/python2.7/site-packages/pandas/io/pytables.py", line 4017, in write
    **kwargs)
  File "/home/drsora/.conda/envs/hase_py2/lib/python2.7/site-packages/pandas/io/pytables.py", line 3704, in create_axes
    self.validate(existing_table)
  File "/home/drsora/.conda/envs/hase_py2/lib/python2.7/site-packages/pandas/io/pytables.py", line 3141, in validate
    c=c, sax=sax, oax=oax))
ValueError: invalid combinate of [values_axes] on appending data [name->CHR,cname->CHR,dtype->string360,kind->string,shape->(1, 100000)] vs current table [name->CHR,cname->CHR,dtype->int64,kind->integer,shape->None]
`

**Comment by epzjlm** [comment]
Just looking at the error in 04b:

Could you check what you see in the probes folder:

source config
ls ${hase_converting}/probes

**Comment by epzjlm** [comment]
For the error in 04a could you check whether your bim and fam file are tab separated in 
source config
$hase_dir_in

**Comment by drsora** [comment]
> For the error in 04a could you check whether your bim and fam file are tab separated in source config $hase_dir_in

Yes, they seem to be tab separated

**Comment by drsora** [comment]
> Just looking at the error in 04b:
> 
> Could you check what you see in the probes folder:
> 
> source config ls ${hase_converting}/probes

These:
YFS_G1_hash_table.csv.gz  YFS_G1_original.h5

**Comment by epzjlm** [comment]
could you check 

source config
ls ${hase_dir_in}
rm ${hase_dir_in}/data.log

**Comment by drsora** [comment]
I'm just thinking that there is a high chance that I mixed up my config files and that's the reason for at least some of the latest errors 🙃 (running this on 3 datasets at the same time is...challenging). I have run the whole module 4 in Luric (there's a comment on the pull request about that) and I will now try to rerun it in YFS G1 and G0 also on chrX and hope for more success.

**Comment by drsora** [comment]
Okay I ran 04a again on YFS G1 and check_upload says it again did not complete successfully (on chrX branch).

**Comment by CLVallerga** [comment]
Hi all, has this issue been solved? I got exactly the same error as @drsora:


"Time to compute partial derivatives : 149.691201925 sec
experiment finished in 425.279926062 s
Closing remaining open files:/home/c.vallerga/GoDMC_Phase2/godmc_phase2/RotterdamStudy_450k_2/processed_data/hase/hase_converting/probes/RotterdamStudy_450k_2.h5...done/home/c.vallerga/GoDMC_Phase2/godmc_phase2/resources/bin/hase/data/ref-hrc.ref_info.h5...done
mv: target '/home/c.vallerga/GoDMC_Phase2/godmc_phase2/RotterdamStudy_450k_2/results/04/mapping/' is not a directory"


I thought that might be related to the fact that within script 04e-single-site-analysis.sh there might be an error at line 38 which I changed from:

**mv ${hase_mapping}/*npy ${home_directory}/results/04/mapping/**

to:

**mv ${hase_mapping}/*npy ${home_directory}/results/04/meta_inputs/mapping/**

But that didn't solve the problem. The error message then becomes the following:

.......
There are 495 ids and 471726 columns
reading file covariates.txt
There are 495 ids and 1 columns
Use ID from mapper
Traceback (most recent call last):
  File "/home/c.vallerga/GoDMC_Phase2/godmc_phase2/resources/bin/hase/hase.py", line 913, in <module>
    sys.exit(main())
  File "/home/c.vallerga/GoDMC_Phase2/godmc_phase2/resources/bin/hase/hase.py", line 356, in main
    gen.start(args.genotype[0], hdf5=args.hdf5, study_name=args.study_name[0], ID=False)
  File "/home/c.vallerga/GoDMC_Phase2/godmc_phase2/resources/bin/hase/hdgwas/data.py", line 1477, in start
    self.folder = PLINKHDF5Folder(path, kwargs['study_name'])
  File "/home/c.vallerga/GoDMC_Phase2/godmc_phase2/resources/bin/hase/hdgwas/data.py", line 977, in __init__
    self._data = Hdf5Data(self.path, self.name)
  File "/home/c.vallerga/GoDMC_Phase2/godmc_phase2/resources/bin/hase/hdgwas/data.py", line 326, in __init__
    self.names = pd.HDFStore(os.path.join(data_path, 'probes', self.name + '.h5'), 'r')
  File "/home/c.vallerga/.conda/envs/hase_py2/lib/python2.7/site-packages/pandas/io/pytables.py", line 488, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/c.vallerga/.conda/envs/hase_py2/lib/python2.7/site-packages/pandas/io/pytables.py", line 603, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/c.vallerga/.conda/envs/hase_py2/lib/python2.7/site-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/c.vallerga/.conda/envs/hase_py2/lib/python2.7/site-packages/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 374, in tables.hdf5extension.File._g_new
  File "/home/c.vallerga/.conda/envs/hase_py2/lib/python2.7/site-packages/tables/utils.py", line 157, in check_file_access
    raise IOError("``%s`` does not exist" % (filename,))
IOError: ``/home/c.vallerga/GoDMC_Phase2/godmc_phase2/RotterdamStudy_450k_2/processed_data/hase/hase_converting/probes/RotterdamStudy_450k_2.h5`` does not exist
Closing remaining open files:/home/c.vallerga/GoDMC_Phase2/godmc_phase2/resources/bin/hase/data/ref-hrc.ref_info.h5...done


I am currently unable to run step 4e for all 4 data sets I have. I will appreciate the help :) 

Costanza

**Comment by epzjlm** [comment]
@drsora I updated check_upload for 04a on the chrX branch. There was a typo. Please try again.
